import { Invoice } from "@/hooks/useInvoices";

export const DeliveryNoteTemplate = ({ invoice }: { invoice: Invoice }) => {
  const fmt = (v: any) => v ?? "–";
  const fmtAmt = (v: any) =>
    v != null ? `₹${Number(v).toLocaleString("en-IN")}/-` : "₹_________/-";

  if (invoice.invoice_type === "purchase") {
    return (
      <div className="bg-white p-8 space-y-6">
        {/* Header */}
        <div className="flex justify-between items-start pb-4 border-b-4 border-teal-700">
          <div className="text-sm text-gray-600 space-y-1">
            <div>
              <strong>PDN NO:</strong>{" "}
              <span className="font-mono">{fmt(invoice.invoice_no)}</span>
            </div>
            <div>
              <strong>PURCHASE DATE & TIME:</strong>{" "}
              {invoice.created_at
                ? new Date(invoice.created_at).toLocaleString("en-IN")
                : "–"}
            </div>
            <div>
              <strong>PURCHASE LOCATION:</strong> {fmt(invoice.location)}
            </div>
            <div>
              <strong>CHANNEL:</strong> {fmt(invoice.channel)}
            </div>
            <div>
              <strong>PDN GENERATED BY:</strong> {fmt(invoice.generated_by)}
            </div>
            <div>
              <strong>PRINTED AT:</strong>{" "}
              {new Date().toLocaleString("en-IN")}
            </div>
          </div>
          <div className="text-right">
            <div className="text-4xl font-black text-gray-800">
              2<span className="text-teal-700">Wheel</span>R
            </div>
            <div className="text-xs text-gray-500">...sabke liye.</div>
          </div>
        </div>
        <div className="bg-gray-800 text-white text-xs font-bold p-2 text-right">
          GST: RIDEONRENT TECHNOLOGIES PRIVATE LIMITED: 27AAHCR4949R1ZD
        </div>

        {/* Title */}
        <div className="bg-gray-600 text-white text-center font-black text-lg uppercase tracking-wider py-3">
          Purchase Delivery Note
        </div>

        {/* Vehicle + RC */}
        <div className="grid grid-cols-2 gap-8">
          <div>
            <h3 className="bg-teal-700 text-white text-xs font-bold p-2 mb-3 rounded uppercase tracking-wider">
              Vehicle Details
            </h3>
            <div className="space-y-2 text-sm">
              <div className="flex justify-between border-b border-dashed pb-1">
                <span className="font-bold text-gray-500 uppercase text-xs">
                  Vehicle Details
                </span>
                <span>{fmt(invoice.bike_model)}</span>
              </div>
              <div className="flex justify-between border-b border-dashed pb-1">
                <span className="font-bold text-gray-500 uppercase text-xs">
                  CC
                </span>
                <span>{fmt(invoice.cc)}</span>
              </div>
              <div className="flex justify-between border-b border-dashed pb-1">
                <span className="font-bold text-gray-500 uppercase text-xs">
                  KMS Driven
                </span>
                <span>{fmt(invoice.kms_driven)}</span>
              </div>
              <div className="flex justify-between border-b border-dashed pb-1">
                <span className="font-bold text-gray-500 uppercase text-xs">
                  Colour
                </span>
                <span>{fmt(invoice.colour)}</span>
              </div>
              <div className="flex justify-between border-b border-dashed pb-1">
                <span className="font-bold text-gray-500 uppercase text-xs">
                  Chassis No.
                </span>
                <span className="font-mono">{fmt(invoice.chassis_no)}</span>
              </div>
              <div className="flex justify-between border-b border-dashed pb-1">
                <span className="font-bold text-gray-500 uppercase text-xs">
                  Engine No.
                </span>
                <span className="font-mono">{fmt(invoice.engine_no)}</span>
              </div>
            </div>
          </div>

          <div>
            <h3 className="bg-teal-700 text-white text-xs font-bold p-2 mb-3 rounded uppercase tracking-wider">
              RC Details
            </h3>
            <div className="space-y-2 text-sm">
              <div className="flex justify-between border-b border-dashed pb-1">
                <span className="font-bold text-gray-500 uppercase text-xs">
                  Registration No.
                </span>
                <span className="font-mono">
                  {fmt(invoice.registration_no)}
                </span>
              </div>
              <div className="flex justify-between border-b border-dashed pb-1">
                <span className="font-bold text-gray-500 uppercase text-xs">
                  Registration Date
                </span>
                <span>{fmt(invoice.registration_date)}</span>
              </div>
              <div className="flex justify-between border-b border-dashed pb-1">
                <span className="font-bold text-gray-500 uppercase text-xs">
                  Registration Year
                </span>
                <span>{fmt(invoice.registration_year)}</span>
              </div>
              <div className="flex justify-between border-b border-dashed pb-1">
                <span className="font-bold text-gray-500 uppercase text-xs">
                  No. of Owners
                </span>
                <span>{fmt(invoice.no_of_owners)}</span>
              </div>
            </div>
          </div>
        </div>

        {/* Owner + Seller */}
        <div className="grid grid-cols-2 gap-8">
          <div>
            <h3 className="bg-teal-700 text-white text-xs font-bold p-2 mb-3 rounded uppercase tracking-wider">
              Original Owner Details
            </h3>
            <div className="space-y-2 text-sm">
              <div className="flex justify-between border-b border-dashed pb-1">
                <span className="font-bold text-gray-500 uppercase text-xs">
                  Seller Type
                </span>
                <span>{fmt(invoice.seller_type)}</span>
              </div>
              <div className="flex justify-between border-b border-dashed pb-1">
                <span className="font-bold text-gray-500 uppercase text-xs">
                  Name
                </span>
                <span>{fmt(invoice.seller_name)}</span>
              </div>
              <div className="flex justify-between border-b border-dashed pb-1">
                <span className="font-bold text-gray-500 uppercase text-xs">
                  Contact No.
                </span>
                <span className="font-mono">{fmt(invoice.mobile)}</span>
              </div>
              <div className="flex justify-between border-b border-dashed pb-1">
                <span className="font-bold text-gray-500 uppercase text-xs">
                  Address
                </span>
                <span className="text-right">
                  {fmt(invoice.seller_address)}
                </span>
              </div>
            </div>
          </div>

          <div>
            <h3 className="bg-teal-700 text-white text-xs font-bold p-2 mb-3 rounded uppercase tracking-wider">
              Seller Details
            </h3>
            <div className="space-y-2 text-sm">
              <div className="flex justify-between border-b border-dashed pb-1">
                <span className="font-bold text-gray-500 uppercase text-xs">
                  Name
                </span>
                <span>{fmt(invoice.seller_name)}</span>
              </div>
              <div className="flex justify-between border-b border-dashed pb-1">
                <span className="font-bold text-gray-500 uppercase text-xs">
                  Contact No.
                </span>
                <span className="font-mono">{fmt(invoice.mobile)}</span>
              </div>
              <div className="flex justify-between border-b border-dashed pb-1">
                <span className="font-bold text-gray-500 uppercase text-xs">
                  Alt Contact No.
                </span>
                <span className="font-mono">{fmt(invoice.alt_mobile)}</span>
              </div>
              <div className="flex justify-between border-b border-dashed pb-1">
                <span className="font-bold text-gray-500 uppercase text-xs">
                  Address
                </span>
                <span className="text-right">
                  {fmt(invoice.seller_address)}
                </span>
              </div>
            </div>
          </div>
        </div>

        {/* Transaction */}
        <div>
          <h3 className="bg-teal-700 text-white text-xs font-bold p-2 mb-3 rounded uppercase tracking-wider">
            Transaction Details
          </h3>
          <div className="grid grid-cols-2 gap-8">
            <div className="space-y-2 text-sm">
              <div className="flex justify-between border-b border-dashed pb-1">
                <span className="font-bold text-gray-500 uppercase text-xs">
                  Purchase Price
                </span>
                <span className="font-mono font-bold text-gray-800">
                  {fmtAmt(invoice.sale_price)}
                </span>
              </div>
            </div>
            <div className="space-y-2 text-sm">
              <div className="flex justify-between border-b border-dashed pb-1">
                <span className="font-bold text-gray-500 uppercase text-xs">
                  Final Payable
                </span>
                <span className="font-mono font-bold text-gray-800">
                  {fmtAmt(invoice.final_price)}
                </span>
              </div>
              <div className="flex justify-between border-b border-dashed pb-1">
                <span className="font-bold text-gray-500 uppercase text-xs">
                  Advance Given
                </span>
                <span className="font-mono font-bold text-gray-800">
                  {fmtAmt(invoice.advance_given)}
                </span>
              </div>
              <div className="flex justify-between border-b border-dashed pb-1">
                <span className="font-bold text-gray-500 uppercase text-xs">
                  Balance Remaining
                </span>
                <span className="font-mono font-bold text-gray-800">
                  {fmtAmt(invoice.balance_remaining)}
                </span>
              </div>
            </div>
          </div>
        </div>

        {/* Signatures */}
        <div className="flex justify-between pt-12 mt-8 border-t">
          <div className="text-center">
            <div className="w-40 border-b-2 border-gray-700 h-20 mb-2"></div>
            <div className="text-xs text-gray-600 font-bold">
              Signature of Punekar Bike Points Representative
            </div>
          </div>
          <div className="text-center">
            <div className="w-40 border-b-2 border-gray-700 h-20 mb-2"></div>
            <div className="text-xs text-gray-600 font-bold">
              Signature of Seller
            </div>
          </div>
        </div>
      </div>
    );
  }

  // SALES DELIVERY NOTE
  return (
    <div className="bg-white p-8 space-y-6">
      {/* Header */}
      <div className="flex justify-between items-start pb-4 border-b-4 border-teal-700">
        <div className="text-sm text-gray-600 space-y-1">
          <div>
            <strong>SDN NO:</strong>{" "}
            <span className="font-mono">{fmt(invoice.invoice_no)}</span>
          </div>
          <div>
            <strong>SALE DATE & TIME:</strong>{" "}
            {invoice.created_at
              ? new Date(invoice.created_at).toLocaleString("en-IN")
              : "–"}
          </div>
          <div>
            <strong>SALE LOCATION:</strong> {fmt(invoice.location)}
          </div>
          <div>
            <strong>CHANNEL:</strong> {fmt(invoice.channel)}
          </div>
          <div>
            <strong>SDN GENERATED BY:</strong> {fmt(invoice.generated_by)}
          </div>
          <div>
            <strong>PRINTED AT:</strong> {new Date().toLocaleString("en-IN")}
          </div>
        </div>
        <div className="text-right">
          <div className="text-4xl font-black text-gray-800">
            2<span className="text-teal-700">Wheel</span>R
          </div>
          <div className="text-xs text-gray-500">...sabke liye.</div>
        </div>
      </div>
      <div className="bg-gray-800 text-white text-xs font-bold p-2 text-right">
        GST: RIDEONRENT TECHNOLOGIES PRIVATE LIMITED: 27AAHCR4949R1ZD
      </div>

      {/* Title */}
      <div className="bg-gray-600 text-white text-center font-black text-lg uppercase tracking-wider py-3">
        Sales Delivery Note
      </div>

      {/* Vehicle Details */}
      <div className="grid grid-cols-2 gap-8">
        <div className="space-y-2 text-sm">
          <div className="flex justify-between border-b border-dashed pb-1">
            <span className="font-bold text-gray-500 uppercase text-xs">
              Registration No.
            </span>
            <span className="font-mono">{fmt(invoice.registration_no)}</span>
          </div>
          <div className="flex justify-between border-b border-dashed pb-1">
            <span className="font-bold text-gray-500 uppercase text-xs">
              Vehicle Details
            </span>
            <span>{fmt(invoice.bike_model)}</span>
          </div>
          <div className="flex justify-between border-b border-dashed pb-1">
            <span className="font-bold text-gray-500 uppercase text-xs">
              KMS Driven
            </span>
            <span>{fmt(invoice.kms_driven)}</span>
          </div>
          <div className="flex justify-between border-b border-dashed pb-1">
            <span className="font-bold text-gray-500 uppercase text-xs">
              No. of Owners
            </span>
            <span>{fmt(invoice.no_of_owners)}</span>
          </div>
        </div>
        <div className="space-y-2 text-sm">
          <div className="flex justify-between border-b border-dashed pb-1">
            <span className="font-bold text-gray-500 uppercase text-xs">
              Registration Year
            </span>
            <span>{fmt(invoice.registration_year)}</span>
          </div>
          <div className="flex justify-between border-b border-dashed pb-1">
            <span className="font-bold text-gray-500 uppercase text-xs">
              Chassis No.
            </span>
            <span className="font-mono">{fmt(invoice.chassis_no)}</span>
          </div>
          <div className="flex justify-between border-b border-dashed pb-1">
            <span className="font-bold text-gray-500 uppercase text-xs">
              Engine No.
            </span>
            <span className="font-mono">{fmt(invoice.engine_no)}</span>
          </div>
        </div>
      </div>

      {/* Buyer Details */}
      <div>
        <h3 className="bg-teal-700 text-white text-xs font-bold p-2 mb-3 rounded uppercase tracking-wider">
          Buyer Details
        </h3>
        <div className="space-y-2 text-sm">
          <div className="flex justify-between border-b border-dashed pb-1">
            <span className="font-bold text-gray-500 uppercase text-xs">
              Full Name
            </span>
            <span>{fmt(invoice.customer_name)}</span>
          </div>
          <div className="flex justify-between border-b border-dashed pb-1">
            <span className="font-bold text-gray-500 uppercase text-xs">
              Contact Number
            </span>
            <span className="font-mono">{fmt(invoice.mobile)}</span>
          </div>
          <div className="flex justify-between border-b border-dashed pb-1">
            <span className="font-bold text-gray-500 uppercase text-xs">
              Local Address
            </span>
            <span className="text-right">{fmt(invoice.address)}</span>
          </div>
          <div className="flex justify-between border-b border-dashed pb-1">
            <span className="font-bold text-gray-500 uppercase text-xs">
              Alt Contact No.
            </span>
            <span className="font-mono">{fmt(invoice.alt_mobile)}</span>
          </div>
        </div>
      </div>

      {/* Transaction */}
      <div>
        <h3 className="bg-teal-700 text-white text-xs font-bold p-2 mb-3 rounded uppercase tracking-wider">
          Transaction Details
        </h3>
        <div className="space-y-2 text-sm">
          <div className="flex justify-between border-b border-dashed pb-1">
            <span className="font-bold text-gray-500 uppercase text-xs">
              Final Selling Price
            </span>
            <span className="font-mono font-bold text-gray-800">
              {fmtAmt(invoice.sale_price)}
            </span>
          </div>
          <div className="flex justify-between border-b border-dashed pb-1">
            <span className="font-bold text-gray-500 uppercase text-xs">
              Total Sale Price
            </span>
            <span className="font-mono font-bold text-gray-800">
              {fmtAmt(invoice.final_price)}
            </span>
          </div>
        </div>
      </div>

      {/* Signatures */}
      <div className="flex justify-between pt-12 mt-8 border-t">
        <div className="text-center">
          <div className="w-40 border-b-2 border-gray-700 h-20 mb-2"></div>
          <div className="text-xs text-gray-600 font-bold">
            Signature of Punekar Bike Points Representative
          </div>
        </div>
        <div className="text-center">
          <div className="w-40 border-b-2 border-gray-700 h-20 mb-2"></div>
          <div className="text-xs text-gray-600 font-bold">
            Signature of Buyer
          </div>
        </div>
      </div>
    </div>
  );
};
