import { useState } from "react";
import type { Invoice } from "@/hooks/useInvoices";

interface InvoiceTemplateProps {
  invoice: Invoice;
  type?: "sales" | "purchase";
}

export const InvoiceTemplate = ({ invoice, type = invoice.invoice_type }: InvoiceTemplateProps) => {
  const [activeTab, setActiveTab] = useState<"purchase" | "sales">(type);

  // Format utilities
  const fmt = (v: any) => v ?? "–";
  const fmtAmt = (v: any) =>
    v != null ? `₹${Number(v).toLocaleString("en-IN")}/-` : "₹_________/-";
  const Badge = ({ value, trueLabel = "Yes", falseLabel = "No" }: any) => (
    <span className={`inline-block px-2 py-0.5 rounded-full text-xs font-bold ${value ? "bg-green-100 text-green-900" : "bg-red-100 text-red-900"}`}>
      {value ? trueLabel : falseLabel}
    </span>
  );

  const FieldRow = ({ label, value, mono = false }: { label: string; value: any; mono?: boolean }) => (
    <div className="grid grid-cols-[170px_1fr] gap-3 py-1 px-0 border-b border-dashed border-gray-300">
      <span className="text-xs font-bold text-gray-500 uppercase tracking-wider pt-0.5">{label}</span>
      <span className={`text-sm font-medium text-gray-900 ${mono ? "font-mono text-xs" : ""}`}>
        {value}
      </span>
    </div>
  );

  const SectionHeading = ({ children }: { children: React.ReactNode }) => (
    <div className="text-xs font-bold uppercase tracking-wider text-white bg-teal-600 px-2.5 py-1 rounded my-4 mb-2.5">
      {children}
    </div>
  );

  const DocPaper = ({ children }: { children: React.ReactNode }) => (
    <div className="bg-white rounded shadow-lg overflow-hidden mb-7 page-break">
      {children}
    </div>
  );

  const DocHeader = ({ meta, showBrand = true }: { meta: any; showBrand?: boolean }) => (
    <>
      <div className="grid grid-cols-[1fr_auto] gap-4 items-start p-5 border-b-4 border-teal-700">
        <div className="text-xs text-gray-600 leading-relaxed">
          <div>
            <strong>
              {activeTab === "purchase" ? "PDN NO:" : "SDN NO:"}
            </strong>{" "}
            <span className="font-mono">{fmt(invoice.invoice_no)}</span>
          </div>
          <div>
            <strong>{activeTab === "purchase" ? "PURCHASE" : "SALE"} DATE &amp; TIME:</strong>{" "}
            {invoice.created_at ? new Date(invoice.created_at).toLocaleString("en-IN") : "–"}
          </div>
          <div>
            <strong>{activeTab === "purchase" ? "PURCHASE" : "SALE"} LOCATION:</strong> {fmt(invoice.location)}
          </div>
          <div>
            <strong>CHANNEL:</strong> {fmt(invoice.channel)}
          </div>
          <div>
            <strong>
              {activeTab === "purchase" ? "PDN" : "SDN"} GENERATED BY:
            </strong>{" "}
            {fmt(invoice.generated_by)}
          </div>
          <div>
            <strong>PRINTED AT:</strong> {new Date().toLocaleString("en-IN")}
          </div>
        </div>
        {showBrand && (
          <div className="text-right">
            <div className="text-3xl font-black text-gray-800 leading-tight">
              2<span className="text-teal-700">Wheel</span>R
            </div>
            <div className="text-xs text-gray-500 mt-0.5">...sabke liye.</div>
          </div>
        )}
      </div>
      <div className="bg-gray-800 text-white text-xs font-semibold tracking-wider text-right px-6 py-1">
        GST: RIDEONRENT TECHNOLOGIES PRIVATE LIMITED: 27AAHCR4949R1ZD
      </div>
    </>
  );

  const DocTitle = ({ children }: { children: React.ReactNode }) => (
    <div className="bg-gray-600 text-white text-center font-black text-lg uppercase tracking-wider py-2.5">
      {children}
    </div>
  );

  // ═══════════════════════════════════════════════════════════
  // PURCHASE DELIVERY NOTE
  // ═══════════════════════════════════════════════════════════
  const PurchaseNote = () => (
    <DocPaper>
      <DocHeader meta={invoice} />
      <DocTitle>Purchase Delivery Note</DocTitle>

      <div className="p-6 space-y-6">
        {/* Vehicle + RC */}
        <div className="grid grid-cols-2 gap-8">
          <div>
            <SectionHeading>Vehicle Details</SectionHeading>
            <FieldRow label="Vehicle Details" value={fmt(invoice.bike_model)} />
            <FieldRow label="CC" value={fmt(invoice.cc)} />
            <FieldRow label="KMS Driven" value={fmt(invoice.kms_driven)} />
            <FieldRow label="Colour" value={fmt(invoice.colour)} />
            <FieldRow label="Chassis No." value={fmt(invoice.chassis_no)} mono />
            <FieldRow label="Engine No." value={fmt(invoice.engine_no)} mono />
            <FieldRow label="Existing Insurance" value={<Badge value={invoice.existing_insurance} />} />
            <FieldRow label="Existing Warranty" value={<Badge value={invoice.existing_warranty} />} />
          </div>
          <div>
            <SectionHeading>RC Details</SectionHeading>
            <FieldRow label="Original RC" value={<Badge value={invoice.original_rc} />} />
            <FieldRow label="Registration No." value={fmt(invoice.registration_no)} mono />
            <FieldRow label="Registration Date" value={fmt(invoice.registration_date)} />
            <FieldRow label="Registration Year" value={fmt(invoice.registration_year)} />
            <FieldRow label="No. of Owners" value={fmt(invoice.no_of_owners)} />
            <FieldRow label="Loan on Vehicle" value={<Badge value={invoice.loan_on_vehicle} />} />
            <FieldRow label="Bank NOC (if applicable)" value="–" />
          </div>
        </div>

        {/* Owner + Seller */}
        <div className="grid grid-cols-2 gap-8">
          <div>
            <SectionHeading>Original Owner Details</SectionHeading>
            <FieldRow label="Inspection Type" value={fmt(invoice.inspection_type)} />
            <FieldRow label="Seller Type" value={fmt(invoice.seller_type)} />
            <FieldRow label="Name" value={fmt(invoice.seller_name)} />
            <FieldRow label="Contact No." value={fmt(invoice.mobile)} mono />
            <FieldRow label="Alt Contact No." value={fmt(invoice.alt_mobile)} mono />
            <FieldRow label="Email ID" value="__________" />
            <FieldRow label="Permanent Address" value={fmt(invoice.seller_address)} />
          </div>
          <div>
            <SectionHeading>Seller Details</SectionHeading>
            <FieldRow label="Is Original Owner the Seller?" value={<Badge value={true} />} />
            <FieldRow label="Name" value={fmt(invoice.seller_name)} />
            <FieldRow label="Contact No." value={fmt(invoice.mobile)} mono />
            <FieldRow label="Alt Contact No." value={fmt(invoice.alt_mobile)} mono />
            <FieldRow label="Email ID" value="__________" />
            <FieldRow label="Permanent Address" value={fmt(invoice.seller_address)} />
          </div>
        </div>

        {/* Documents */}
        <div>
          <SectionHeading>Documents for Transfer</SectionHeading>
          <div className="grid grid-cols-2 gap-8">
            <div>
              <div className="text-xs font-bold uppercase tracking-wider text-white bg-teal-500 px-2.5 py-1 rounded mb-2.5">
                Vehicle Documents
              </div>
              <FieldRow label="Original RC" value={<Badge value={true} />} />
              <FieldRow label="Insurance Copy" value={<Badge value={false} />} />
              <FieldRow label="Bank NOC (if applicable)" value={<Badge value={false} />} />
              <FieldRow label="Other Documents" value="–" />
            </div>
            <div>
              <div className="text-xs font-bold uppercase tracking-wider text-white bg-teal-500 px-2.5 py-1 rounded mb-2.5">
                Original Owner Documents
              </div>
              <FieldRow label="Aadhaar Card" value={<Badge value={true} />} />
              <FieldRow label="Aadhaar Number" value={fmt(invoice.aadhaar_no)} mono />
              <FieldRow label="PAN Card" value={<Badge value={true} />} />
              <FieldRow label="PAN Number" value={fmt(invoice.pan_no)} mono />
            </div>
          </div>
        </div>

        {/* Transaction */}
        <div>
          <SectionHeading>Transaction Details</SectionHeading>
          <div className="grid grid-cols-2 gap-8">
            <div>
              <FieldRow label="Purchase Price" value={fmtAmt(invoice.sale_price)} />
              <FieldRow label="Existing Challan" value={<Badge value={false} />} />
              <FieldRow label="Challan Amount" value="₹0/-" />
            </div>
            <div>
              <FieldRow label="Final Payable Purchase Price" value={fmtAmt(invoice.final_price ?? invoice.sale_price)} />
              <FieldRow label="Advance Given" value={fmtAmt(invoice.advance_given)} />
              <FieldRow label="Balance Remaining" value={fmtAmt(invoice.balance_remaining ?? 0)} />
            </div>
          </div>
        </div>

        {/* Signatures */}
        <div className="flex justify-between items-end mt-9 pt-4 border-t border-gray-300">
          <div className="text-center">
            <div className="w-40 border-b-2 border-gray-800 mb-1 h-9"></div>
            <div className="text-xs text-gray-600 font-semibold">Signature of 2WheelR Representative</div>
          </div>
          <div className="text-center">
            <div className="w-40 border-b-2 border-gray-800 mb-1 h-9"></div>
            <div className="text-xs text-gray-600 font-semibold">Signature of Seller</div>
          </div>
        </div>
      </div>
    </DocPaper>
  );

  // ═══════════════════════════════════════════════════════════
  // SALES DELIVERY NOTE - PAGE 1
  // ═══════════════════════════════════════════════════════════
  const SalesNotePage1 = () => (
    <DocPaper>
      <DocHeader meta={invoice} />
      <DocTitle>Sales Delivery Note</DocTitle>

      <div className="p-6 space-y-6">
        {/* Vehicle */}
        <div className="grid grid-cols-2 gap-8">
          <div>
            <SectionHeading>Vehicle Details</SectionHeading>
            <FieldRow label="Registration No." value={fmt(invoice.registration_no)} mono />
            <FieldRow label="Vehicle Details" value={fmt(invoice.bike_model)} />
            <FieldRow label="KMS Driven" value={fmt(invoice.kms_driven)} />
            <FieldRow label="No. of Owners" value={fmt(invoice.no_of_owners)} />
            <FieldRow label="CC" value={fmt(invoice.cc)} />
            <FieldRow label="Color" value={fmt(invoice.colour)} />
          </div>
          <div>
            <div style={{ visibility: "hidden" }} className="text-xs font-bold uppercase">
              spacer
            </div>
            <FieldRow label="Date as on RC" value={fmt(invoice.registration_date)} />
            <FieldRow label="Registration Year" value={fmt(invoice.registration_year)} />
            <FieldRow label="Chassis No." value={fmt(invoice.chassis_no)} mono />
            <FieldRow label="Engine No." value={fmt(invoice.engine_no)} mono />
            <FieldRow label="Exchange Vehicle?" value={<Badge value={false} trueLabel="YES" falseLabel="NO" />} />
            <FieldRow label="Exchange Reg No." value="–" />
          </div>
        </div>

        {/* Buyer */}
        <SectionHeading>Buyer Details</SectionHeading>
        <FieldRow label="Full Name" value={fmt(invoice.customer_name)} />
        <FieldRow label="Contact Number" value={fmt(invoice.mobile)} mono />
        <FieldRow label="Local Address" value={fmt(invoice.address)} />
        <FieldRow label="Email ID" value="________________________________" />
        <FieldRow label="Alt Contact No." value={fmt(invoice.alt_mobile)} mono />
        <FieldRow label="Permanent Address" value={fmt(invoice.address)} />

        {/* Documents */}
        <SectionHeading>Documents</SectionHeading>
        <div className="grid grid-cols-2 gap-8">
          <div>
            <FieldRow label="Original RC" value={<Badge value={true} />} />
            <FieldRow label="Chassis Copy" value={<Badge value={false} />} />
            <FieldRow label="Bank NOC (if applicable)" value={<Badge value={false} />} />
            <FieldRow label="Insurance Copy" value={<Badge value={true} />} />
          </div>
          <div>
            <FieldRow label="Aadhaar Card" value={<Badge value={true} />} />
            <FieldRow label="PAN Card" value={<Badge value={true} />} />
            <FieldRow label="Electricity Bill" value={<Badge value={true} />} />
            <FieldRow label="Rent Agreement" value={<Badge value={false} />} />
          </div>
        </div>

        {/* Warranty */}
        <SectionHeading>Warranty Details</SectionHeading>
        <FieldRow label="Is Warranty Applicable (Y/N)?" value={<Badge value={invoice.warranty_applicable} />} />
        <FieldRow label="Warranty (if applicable) Expiry Date" value={fmt(invoice.warranty_expiry)} />

        {/* Transaction */}
        <SectionHeading>Transaction Details</SectionHeading>
        <FieldRow label="Final Selling Price" value={fmtAmt(invoice.sale_price)} />
        <FieldRow label="RTO Charges" value="__________/-" />
        <FieldRow label="TCS (if applicable)" value="–" />
        <FieldRow label="Total Sale Price" value={fmtAmt(invoice.final_price ?? invoice.sale_price)} />

        {/* Signatures */}
        <div className="flex justify-between items-end mt-9 pt-4 border-t border-gray-300">
          <div className="text-center">
            <div className="w-40 border-b-2 border-gray-800 mb-1 h-9"></div>
            <div className="text-xs text-gray-600 font-semibold">Signature of 2WheelR Representative</div>
          </div>
          <div className="text-center">
            <div className="w-40 border-b-2 border-gray-800 mb-1 h-9"></div>
            <div className="text-xs text-gray-600 font-semibold">Signature of Buyer</div>
          </div>
        </div>
      </div>
    </DocPaper>
  );

  // ═══════════════════════════════════════════════════════════
  // SALES DELIVERY NOTE - PAGE 2 (Terms & Conditions)
  // ═══════════════════════════════════════════════════════════
  const SalesNotePage2 = () => (
    <DocPaper>
      <DocHeader meta={invoice} />
      <DocTitle>Sales Delivery Note</DocTitle>

      <div className="p-6">
        <SectionHeading>Terms &amp; Conditions</SectionHeading>

        <div className="space-y-4">
          <div>
            <div className="font-bold text-sm mb-2">Terms for Warranty</div>
            <p className="text-sm mb-2">2WheelR Warranty is applicable:</p>
            <ul className="text-xs space-y-1 ml-4">
              <li>
                <strong>ONLY IF</strong> mentioned under <strong>"Warranty Details Section"</strong> of the Sales Delivery Note.
              </li>
              <li>
                <strong>ONLY</strong> for those customers who purchase a pre-owned 2-wheeler from 2WheelR (including all 2WheelR company owned stores and franchises).
              </li>
              <li>
                <strong>ONLY</strong> covers bikes under 150cc that are 7 years or younger from date of sale as mentioned on the Sales Delivery Note.
              </li>
              <li>
                <strong>ONLY</strong> Engine and Gearbox for bikes under 150cc that are 7 years or younger from date of sale as mentioned on the Sales Delivery Note.
              </li>
              <li>
                <strong>ONLY</strong> for <strong>30 days from the date of bike sale.</strong>
              </li>
              <li>
                <strong>ONLY</strong> if the defect(s) are within the terms and conditions specified.
              </li>
              <li>
                After the expiry of warranty, if the customer wants to get their bike serviced from the company, the bill will be raised by the company and <strong>it will be at the expense to the customer.</strong>
              </li>
              <li>
                RC Transfer Process completion shall be within a period of 60–90 days from the date of submission of all documents required for transfer by the buyer of the vehicle.
              </li>
            </ul>
          </div>

          <div>
            <div className="font-bold text-sm mb-2">
              2WheelR Warranty <span className="text-red-600">DOES NOT COVER</span>:
            </div>
            <ul className="text-xs space-y-1 ml-4">
              <li>Bikes/Motorcycles above 151cc</li>
              <li>Clutch plates and pressure plates</li>
              <li>Suspension</li>
              <li>Tyres, cosmetics, Rims</li>
            </ul>
          </div>

          <p className="text-xs font-bold mt-3">Registration Certificate (RC) / Delivery Note receipt should be available at the time of claim.</p>

          <div className="text-xs p-3 bg-teal-50 border-l-4 border-teal-700 rounded mt-3">
            To claim warranty benefits please, call us on <strong>+91 8483893934</strong> OR email us at <strong>support@2wheelr.com</strong>
          </div>
        </div>

        {/* Signatures */}
        <div className="flex justify-between items-end mt-9 pt-4 border-t border-gray-300">
          <div className="text-center">
            <div className="w-40 border-b-2 border-gray-800 mb-1 h-9"></div>
            <div className="text-xs text-gray-600 font-semibold">Signature of 2WheelR Representative</div>
          </div>
          <div className="text-center">
            <div className="w-40 border-b-2 border-gray-800 mb-1 h-9"></div>
            <div className="text-xs text-gray-600 font-semibold">Signature of Buyer</div>
          </div>
        </div>
      </div>
    </DocPaper>
  );

  // ═══════════════════════════════════════════════════════════
  // SALES DELIVERY NOTE - PAGE 3 (Loan & Transaction Log)
  // ═══════════════════════════════════════════════════════════
  const SalesNotePage3 = () => {
    let balance = Number(invoice.final_price ?? invoice.sale_price ?? 0);
    const rows = (invoice.payments ?? []).map((p) => {
      balance -= Number(p.amount);
      return {
        date: new Date(p.date).toLocaleDateString("en-IN"),
        amount: `₹${Number(p.amount).toLocaleString("en-IN")}`,
        txnId: p.transaction_id ?? "–",
        method: p.method ?? "–",
        balance: `₹${balance.toLocaleString("en-IN")}`,
      };
    });

    return (
      <DocPaper>
        <DocHeader meta={invoice} />
        <DocTitle>Sales Delivery Note</DocTitle>

        <div className="p-6 space-y-6">
          <SectionHeading>Loan Details</SectionHeading>
          <FieldRow label="Loan" value={<Badge value={invoice.loan} />} />
          <FieldRow label="Downpayment" value={invoice.loan ? fmtAmt(invoice.downpayment) : "–"} />
          <FieldRow label="Disbursed Amount" value={invoice.loan ? fmtAmt(invoice.disbursed_amount) : "–"} />
          <FieldRow label="Finance Partner" value={fmt(invoice.finance_partner)} />

          <div className="my-3.5 text-xs">
            <strong>Remarks, if any:</strong>
            <span className="inline-block border-b border-gray-400 w-60 ml-2">______________________________</span>
          </div>

          {/* Transaction table */}
          <table className="w-full text-xs border-collapse mt-2.5">
            <thead>
              <tr className="bg-gray-600 text-white">
                <th className="p-2 text-left font-bold uppercase">Transaction Date</th>
                <th className="p-2 text-left font-bold uppercase">Amount Paid</th>
                <th className="p-2 text-left font-bold uppercase">Transaction ID</th>
                <th className="p-2 text-left font-bold uppercase">Payment Method</th>
                <th className="p-2 text-left font-bold uppercase">Balance Remaining</th>
              </tr>
            </thead>
            <tbody>
              {rows.map((row, i) => (
                <tr key={i} className={i % 2 === 0 ? "bg-gray-100" : "bg-white"}>
                  <td className="p-2 border-b border-gray-300">{row.date}</td>
                  <td className="p-2 border-b border-gray-300 font-mono">{row.amount}</td>
                  <td className="p-2 border-b border-gray-300 font-mono">{row.txnId}</td>
                  <td className="p-2 border-b border-gray-300">{row.method}</td>
                  <td className="p-2 border-b border-gray-300 font-mono">{row.balance}</td>
                </tr>
              ))}
              <tr className="bg-teal-50">
                <td colSpan={3}></td>
                <td className="p-2 font-bold">BALANCE PENDING</td>
                <td className="p-2 font-bold font-mono">₹{Math.max(0, balance).toLocaleString("en-IN")}</td>
              </tr>
            </tbody>
          </table>

          {/* Signatures */}
          <div className="flex justify-between items-end mt-9 pt-4 border-t border-gray-300">
            <div className="text-center">
              <div className="w-40 border-b-2 border-gray-800 mb-1 h-9"></div>
              <div className="text-xs text-gray-600 font-semibold">Signature of 2WheelR Representative</div>
            </div>
            <div className="text-center">
              <div className="w-40 border-b-2 border-gray-800 mb-1 h-9"></div>
              <div className="text-xs text-gray-600 font-semibold">Signature of Buyer</div>
            </div>
          </div>
        </div>
      </DocPaper>
    );
  };

  return (
    <div className="min-h-screen bg-gray-200 p-4">
      {/* App Bar */}
      <div className="sticky top-0 z-100 bg-gray-900 text-white flex items-center justify-between px-7 h-13 shadow-lg mb-4">
        <div className="font-black text-xl tracking-wide">
          2<span className="text-teal-600">Wheel</span>R <span className="text-xs font-normal text-gray-400 ml-2.5">Delivery Notes</span>
        </div>
        <div className="flex gap-1.5">
          <button
            onClick={() => setActiveTab("purchase")}
            className={`px-4.5 py-1.5 rounded-full border-2 font-black text-xs tracking-wider uppercase transition-all cursor-pointer ${
              activeTab === "purchase"
                ? "bg-teal-700 text-white border-teal-700"
                : "bg-transparent text-gray-400 border-transparent hover:text-teal-700 hover:border-teal-700"
            }`}
          >
            Purchase Delivery Note
          </button>
          <button
            onClick={() => setActiveTab("sales")}
            className={`px-4.5 py-1.5 rounded-full border-2 font-black text-xs tracking-wider uppercase transition-all cursor-pointer ${
              activeTab === "sales"
                ? "bg-teal-700 text-white border-teal-700"
                : "bg-transparent text-gray-400 border-transparent hover:text-teal-700 hover:border-teal-700"
            }`}
          >
            Sales Delivery Note
          </button>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-4xl mx-auto">
        {activeTab === "purchase" && <PurchaseNote />}
        {activeTab === "sales" && (
          <>
            <SalesNotePage1 />
            <SalesNotePage2 />
            <SalesNotePage3 />
          </>
        )}
      </div>

      {/* Print styles */}
      <style>{`
        @media print {
          .sticky { position: static; }
          .page-break { page-break-after: always; }
        }
      `}</style>
    </div>
  );
};

export default InvoiceTemplate;
