ALTER TABLE public.invoices
  ADD COLUMN IF NOT EXISTS location text,
  ADD COLUMN IF NOT EXISTS channel text,
  ADD COLUMN IF NOT EXISTS generated_by text,
  ADD COLUMN IF NOT EXISTS cc text,
  ADD COLUMN IF NOT EXISTS kms_driven integer,
  ADD COLUMN IF NOT EXISTS colour text,
  ADD COLUMN IF NOT EXISTS registration_date date,
  ADD COLUMN IF NOT EXISTS registration_year text,
  ADD COLUMN IF NOT EXISTS no_of_owners text,
  ADD COLUMN IF NOT EXISTS seller_type text,
  ADD COLUMN IF NOT EXISTS seller_name text,
  ADD COLUMN IF NOT EXISTS seller_address text,
  ADD COLUMN IF NOT EXISTS alt_mobile text,
  ADD COLUMN IF NOT EXISTS advance_given numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS balance_remaining numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS aadhaar_no text,
  ADD COLUMN IF NOT EXISTS pan_no text,
  ADD COLUMN IF NOT EXISTS original_rc boolean,
  ADD COLUMN IF NOT EXISTS existing_insurance boolean,
  ADD COLUMN IF NOT EXISTS existing_warranty boolean,
  ADD COLUMN IF NOT EXISTS loan_on_vehicle boolean,
  ADD COLUMN IF NOT EXISTS inspection_type text,
  ADD COLUMN IF NOT EXISTS warranty_applicable boolean,
  ADD COLUMN IF NOT EXISTS warranty_expiry date,
  ADD COLUMN IF NOT EXISTS loan boolean,
  ADD COLUMN IF NOT EXISTS downpayment numeric,
  ADD COLUMN IF NOT EXISTS disbursed_amount numeric,
  ADD COLUMN IF NOT EXISTS finance_partner text,
  ADD COLUMN IF NOT EXISTS payments jsonb DEFAULT '[]'::jsonb;